component: user
service:
  port: 80
  containerPort: 8080

initContainers:
  parameters_pull:
    image: 367241114876.dkr.ecr.us-east-1.amazonaws.com/default/parameter-store-init-container-image:1.0.0
    imagePullPolicy: Always

containers:
  main:
    image: 367241114876.dkr.ecr.us-east-1.amazonaws.com/default/user:1.0.0
    imagePullPolicy: Always

volumeMounts:
  - name: parameters
    mountPath: /parameters